### ISSUE TITLE
dial tcp 142.251.42.241:443: i/o timeout

### ISSUE THREAD

**Issue by chris-fung** [Gelio/go-global-update#21]
while I run: go install github.com/Gelio/go-global-update@latest,
 I got the error bellow:

go: github.com/Gelio/go-global-update@latest: module github.com/Gelio/go-global-update: Get "https://proxy.golang.org/github.com/%21gelio/go-global-update/@v/list": dial tcp 142.251.42.241:443: i/o timeout

**Comment by chris-fung** [comment]
I use windows 11 wsl(ubuntu 22)

**Comment by Gelio** [comment]
Thanks for the bug report!

Are you able to install other packages from GitHub, like [gomplate](https://docs.gomplate.ca/installing/#install-with-go-install)

```sh
go install github.com/hairyhenderson/gomplate/v4/cmd/gomplate@latest
```

It's hard to tell what the exact problem is. I believe it's some connectivity issue between you and GitHub. If you can, try installing again using a different network (e.g. a hotspot from your phone instead of WiFi). Maybe that helps

**Comment by Gelio** [comment]
@chris-fung Did you manage to fix the problem? Have you tried the steps I mentioned?

**Comment by Gelio** [comment]
I am closing the issue due to lack of inactivity. @chris-fung if you believe this issue is related to this project, feel free to open the issue with a proper reason
